version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 25
  rebase-strategy: "auto"
  labels:
    - "Microsoft package updates"
    
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"