version: 2
updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: daily
    commit-message:
      prefix: "build"
      include: "scope"
    open-pull-requests-limit: 25
    rebase-strategy: "auto"
    labels:
      - "Microsoft package updates"
    groups:
      nuget-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "AWSSDK.Core"
        update-types: [ "version-update:semver-patch" ]
      - dependency-name: "AWSSDK.CloudWatchLogs"
        update-types: [ "version-update:semver-patch" ]
      - dependency-name: "AWSSDK.Extensions.NETCore.Setup"
        update-types: [ "version-update:semver-patch" ]

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    commit-message:
      prefix: "build"
      include: "scope"

  - package-ecosystem: npm
    directory: "/test/CallMyTrade.Api.AcceptanceTests"
    schedule:
      interval: daily
    commit-message:
      prefix: "build"
      include: "scope"
    groups:
      npm-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      vitest:
        patterns:
          - "vitest"
          - "vitest/ui"
