services:
  callmytrade.api:
    image: ghcr.io/khavishbhundoo/callmytrade-api:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - CallMyTrade__Enabled=true
      - CallMyTrade__VoIpProvider=Twilio
      - CallMyTrade__VoIpProvidersOptions__Twilio__TwilioAccountSid=AC70ed67c830a959ef708f6167c1ac6edc
      - CallMyTrade__VoIpProvidersOptions__Twilio__TwilioAuthToken=1c8564ee33609cb1c845831f487e27ac
      - CallMyTrade__VoIpProvidersOptions__Twilio__ToPhoneNumber=+14108675310
      - CallMyTrade__VoIpProvidersOptions__Twilio__FromPhoneNumber=+15005550006
    ports:
      - 80:8080