# fly.toml app configuration file generated for callmytrade-api on 2024-05-12T19:54:32+04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'callmytrade-api'
primary_region = 'lax'

[build]
  image = 'ghcr.io/khavishbhundoo/callmytrade-api:latest'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  

[deploy]
  strategy = "bluegreen"
  
[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/_system/health"