name: Deploy to ECR

on:
  push:
    tags:
       - '*'

env:
  ECR_REPOSITORY: app-repo
  IMAGE_TAG: ${{ github.ref_name }}

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
           fetch-depth: '0'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:  ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Create Docker Cache Storage Backend
        run: |
            docker buildx create --use --driver=docker-container

      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: 'linux/arm64,linux/amd64'
          push: true
          tags: "${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}"
      
      - name: Scan Docker image
        id: docker-scan
        uses: alexjurkiewicz/ecr-scan-image@v2.0.0
        with:
          repository: ${{ env.ECR_REPOSITORY }}
          tag: "${{ env.IMAGE_TAG }}"
          fail_threshold: critical